Do not print extra long fatal error stack when build fails.
The stack just shows where the error comes from,
in the bazel compile driver stack, but has nothing to do
with problems in the code being compiled, adding to the noise.

The program will call `(exit 1)` instead.

The issue was originally reported by Martin Cracauer.

New behavior (redacted):
```
INFO: Found 89 targets...
ERROR: .../BUILD:25:13: Compiling ....lisp failed: (Exit 1) image failed: error executing LispCompile command (from target ...) blaze-out/k8-fastbuild/bin/lisp/devtools/bazel/image --dynamic-space-size 5GB compile --compilation-mode fastbuild --bindir blaze-out/k8-fastbuild/bin --features ... (remaining 7 arguments skipped).  [forge_remote_host=ixoc20]
;
; caught ERROR:
;   READ error during COMPILE-FILE: Package ... does not exist. Line: 26, Column: 55, File-Position: 649 Stream: #<SB-INT:FORM-TRACKING-STREAM for "file /build/work/07cd1964826b6420a5bc2d7c6989297635e3/ ..." {10076E1443}>
;
; compilation unit finished
;   caught 1 fatal ERROR condition
;   caught 1 ERROR condition
FATAL: Files (... .lisp) failed to compile.
BAZEL.LOG:FATAL-ERROR: Files (... lisp) failed to compile. while executing: COMPILE
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 21.505s, Forge stats: 24/1371 actions cached, 28.7m CPU used, 0.1s queue time, 588.3 MB ObjFS output (novel bytes: 259.3 MB), 0.0 MB local output, Critical Path: 19.50s, Remote (75.84% of the time): [queue: 0.00%, setup: 25.00%, process: 28.09%]
ERROR: Build did NOT complete successfully
```

Old behavior added a backtrace through the bazel driver:
```
Backtrace for: #<SB-THREAD:THREAD tid=10082 "main thread" RUNNING {10113A0073}>
0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<BAZEL.LOG:FATAL-ERROR {1007705423}> #<unused argument> :QUIT T)
1: (SB-DEBUG::RUN-HOOK *INVOKE-DEBUGGER-HOOK* #<BAZEL.LOG:FATAL-ERROR {1007705423}>)
2: (INVOKE-DEBUGGER #<BAZEL.LOG:FATAL-ERROR {1007705423}>)
3: (ERROR BAZEL.LOG:FATAL-ERROR :MESSAGE "Files (...) failed to compile.")
4: ((FLET "THUNK" :IN BAZEL.LOG:FATAL))
5: (SB-IMPL::%WITH-STANDARD-IO-SYNTAX #<FUNCTION (FLET "THUNK" :IN BAZEL.LOG:FATAL) {7F0EC4BD785B}>)
6: (BAZEL.LOG:FATAL "Files ~A failed to compile." (...))
7: (BAZEL.MAIN::%COMPILE-SOURCES (...) "..." :SAVE-LOCATIONS NIL :READTABLE #<unavailable argument> :BLOCK-COMPILE #<unavailable argument>)
8: ((:METHOD BAZEL.MAIN:FINISH-ACTION (BAZEL.MAIN:ACTION (EQL :COMPILE))) #<BAZEL.MAIN:ACTION :command :COMPILE :outputs 3 :compilation-mode :FASTBUILD :failures 0 :deferred 0 :muffled 50 :infos 3084> #<unused argument>) [fast-method]
9: (BAZEL.MAIN::PROCESS #<unavailable argument> #<unavailable &REST argument> :DEPS #<unused argument> :LOAD #<unused argument> :SRCS #<unavailable argument> :OUTS #<unavailable argument> :BINDIR #<unavailable argument> :WARNINGS #<unavailable argument
> :HASHES #<unavailable argument> :SPECS #<unavailable argument> :COMPILATION-MODE #<unavailable argument> :BLOCK-COMPILE #<unavailable argument> :BLOCK-COMPILE-SPECIFIED-ONLY #<unavailable argument> :FORCE #<unavailable argument> :MAIN #<unavailable a
rgument> :FEATURES #<unavailable argument> :NOWARN #<unavailable argument> :PRECOMPILE-GENERICS #<unavailable argument> :SAVE-RUNTIME-OPTIONS #<unavailable argument> :COVERAGE #<unavailable argument> :VERBOSE #<unavailable argument> :INTERACTIVE #<unav
ailable argument>)
10: ((SB-PCL::EMF BAZEL.MAIN:EXECUTE-COMMAND) #<unused argument> #<unused argument> :COMPILE :COMPILATION-MODE "fastbuild" :BINDIR "blaze-out/k8-fastbuild/bin" :FEATURES "google3 sb-fasteval os-provides-getprotoby-r largefile immobile-code sb-bsd-socke
ts-addrinfo cffi-sys::flat-namespace http2 rpc2 cl-protobufs" :OUTS #<(SIMPLE-ARRAY CHARACTER (202)) ... blaze-out/k8-fastbuild/bin/... {10012209BF}> :SRCS "travel/qpx/api/lib/fare.lisp" :DEPS #<(SIMPLE-ARRAY CHARACTER (12941)) third_party/lisp/ace/core/collect.lisp third_party/lisp/ace/core/core.lisp third_party/lisp/ace/core/macro.
lisp third_party/lisp/ace/core/type.lisp third_party/lisp/ace/core/check.lisp third_party/lis... {100123000F}>)
11: ((:METHOD BAZEL.MAIN:EXECUTE-COMMAND :AROUND (T)) #<unavailable argument> #<unavailable &REST argument>) [fast-method]
12: ((FLET SB-UNIX::BODY :IN SB-IMPL::START-LISP))
13: ((FLET "WITHOUT-INTERRUPTS-BODY-3" :IN SB-IMPL::START-LISP))
14: (SB-IMPL::%START-LISP)

```

PiperOrigin-RevId: 554967953